steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - >-
        docker build buildx
        --platform linux/amd64
        --build-arg DATABASE_URL=$$DATABASE_URL
        --tag $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
        --tag $_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
        --file Dockerfile
        --cache-from $_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
        --push
        .
    dir: "my-app"
    automapSubstitutions: true
    secretEnv: ["DATABASE_URL"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "app"
      - "--image"
      - "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
      - "--region"
      - "$_REGION"
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
images:
  - "$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
