steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "--build-arg",
        "DATABASE_URL=$$DATABASE_URL",
        "-t",
        "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest",
        "-f",
        "./Dockerfile",
        "--push",
        ".",
      ]
    dir: "my-app"
    automapSubstitutions: true
    secretEnv: ["DATABASE_URL"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "app"
      - "--image"
      - "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - "--region"
      - "$_REGION"
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
images:
  - "$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
