steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/artifact-registry-nextjs-gcp-sample-app/console:latest",
        "-f",
        "./Dockerfile",
        "--push",
        ".",
      ]
    dir: "my-app"
    automapSubstitutions: true
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "app2"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/artifact-registry-nextjs-gcp-sample-app/console:latest"
      - "--region"
      - "ap-northeast1"
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/artifact-registry-nextjs-gcp-sample-app/console:latest"
